#! /bin/bash

export FIGNORE=".o:.pyc:~"
set -b

alias ls='ls --color=auto --group-directories-first'
alias lsl='ls -alh --color=auto --group-directories-first'
alias g='egrep'
alias srcrc='source ~/.bashrc'
alias rmtmp='rm `ls -a | grep "~$"`'
alias df='df -h'
alias du='du -h'
alias tmus='tmux'
alias apache-start='sudo /etc/init.d/apache2 start'
alias apache-stop='sudo /etc/init.d/apache2 stop'
#alias tmx='tmux attach'

function tmx {
	echo "TMUX"
	tmux ls &>/dev/null
	if [[ $? -eq 1 ]]
	then
		echo "starting new"
		tmux
	else
		echo "trying to attach"
		tmux attach
	fi
}

function s3put {
	s3cmd -r put "$@" s3://aswild-bucket/
}
function s3get {
	for i in "$@"; do
		wget http://aswild-bucket.s3.amazonaws.com/$i
	done
}

#export PATH=~/bin:~/bin/gcc-arm-none-eabi/bin:$PATH
export PATH=~/bin:$PATH

#PS1='\[\e[1;32m\][\u@\h \[\e[1;36m\]\W\[\e[1;32m\]]\$\[\e[0m\] '
PS1='\[\e[1;32m\][\u@\[\e[1;34m\]\h \[\e[1;36m\]\W\[\e[1;32m\]]\$\[\e[0m\] '
eval `dircolors ~/.dircolors`
stty -ixon
