#! /bin/zsh

export FIGNORE=".o:.pyc:~"

unsetopt AUTO_CD

alias ls='ls --color=auto --group-directories-first'
alias lsl='ls -alh --color=auto --group-directories-first'
alias g='egrep'
alias srcrc='source ~/.zshrc'
alias rmtmp='rm `ls -a | grep "~$"`'
alias df='df -h'
alias du='du -h'
alias tmus='tmux'
alias psa='ps aux'

alias ifconfig='sudo ifconfig'
alias ifdown='sudo ifdown'
alias ifup='sudo ifup'
alias ip='sudo ip'
alias route='sudo route'
alias 'apt-get'='sudo apt-get'

function tmx {
	echo "TMUX"
	tmux ls &>/dev/null
	if [[ $? -eq 1 ]]
	then
		echo "starting new"
		tmux
	else
		echo "trying to attach"
		tmux attach
	fi
}

#export PATH=~/bin:$PATH

eval `dircolors ~/.dircolors`
stty -ixon

function tftput
{
    #echo -e "binary\nput $1\nquit\n" | tftp 10.10.0.100
    tftp 10.10.0.100 <<END_SCRIPT
    binary
    put $1 $2
    quit
END_SCRIPT
    echo ''
}
